import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Áo Thun Nam Basic",
    price: 299000,
    image: "/placeholder.svg?height=220&width=280&text=Áo+Thun+Nam",
    category: "Áo",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Trắng", "Đen", "Xám"],
    description: "Áo thun nam chất liệu cotton 100%, form regular fit, phù hợp mặc hàng ngày",
    stock: 50,
  },
  {
    id: "2",
    name: "Quần Jeans Slim Fit",
    price: 599000,
    image: "/placeholder.svg?height=220&width=280&text=Quần+Jeans",
    category: "Quần",
    sizes: ["28", "29", "30", "31", "32"],
    colors: ["Xanh đen", "Xanh nhạt"],
    description: "Quần jeans nam slim fit, chất liệu denim cao cấp, thiết kế hiện đại",
    stock: 30,
  },
  {
    id: "3",
    name: "Áo Sơ Mi Trắng",
    price: 450000,
    image: "/placeholder.svg?height=220&width=280&text=Áo+Sơ+Mi",
    category: "Áo",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Trắng", "Xanh nhạt"],
    description: "Áo sơ mi trắng công sở, chất liệu cotton pha, dễ dàng là ủi",
    stock: 25,
  },
  {
    id: "4",
    name: "Váy Midi Hoa",
    price: 399000,
    image: "/placeholder.svg?height=220&width=280&text=Váy+Midi",
    category: "Váy",
    sizes: ["S", "M", "L"],
    colors: ["Hoa đỏ", "Hoa xanh"],
    description: "Váy midi họa tiết hoa, chất liệu voan mềm mại, phù hợp dạo phố",
    stock: 20,
  },
  {
    id: "5",
    name: "Áo Khoác Hoodie",
    price: 699000,
    image: "/placeholder.svg?height=220&width=280&text=Hoodie",
    category: "Áo khoác",
    sizes: ["M", "L", "XL"],
    colors: ["Đen", "Xám", "Navy"],
    description: "Áo khoác hoodie unisex, chất liệu nỉ ấm áp, phù hợp mùa đông",
    stock: 35,
  },
  {
    id: "6",
    name: "Chân Váy Pleat",
    price: 320000,
    image: "/placeholder.svg?height=220&width=280&text=Chân+Váy",
    category: "Váy",
    sizes: ["S", "M", "L"],
    colors: ["Đen", "Xám", "Navy"],
    description: "Chân váy xếp ly, thiết kế trẻ trung, dễ phối đồ",
    stock: 28,
  },
  {
    id: "7",
    name: "Áo Polo Nam",
    price: 350000,
    image: "/placeholder.svg?height=220&width=280&text=Áo+Polo",
    category: "Áo",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Trắng", "Đen", "Navy", "Đỏ"],
    description: "Áo polo nam cổ điển, chất liệu cotton cao cấp",
    stock: 40,
  },
  {
    id: "8",
    name: "Quần Short Kaki",
    price: 280000,
    image: "/placeholder.svg?height=220&width=280&text=Quần+Short",
    category: "Quần",
    sizes: ["28", "29", "30", "31", "32"],
    colors: ["Kaki", "Đen", "Navy"],
    description: "Quần short kaki nam, phù hợp mùa hè",
    stock: 35,
  },
]

export const categories = [
  { name: "Áo", icon: "👕", count: 3 },
  { name: "Quần", icon: "👖", count: 2 },
  { name: "Váy", icon: "👗", count: 2 },
  { name: "Áo khoác", icon: "🧥", count: 1 },
]
